apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zmrr3jvh4-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zmrr3jvh4-dotnet-basic-gitops